In [1]:
import pandas as pd
import numpy as num
file='hollys_branches.csv'
df = pd.read_csv(file)

In [2]:
df

,매장이름,"위치(시,구)",주소,전화번호
0,순천조례점2,전남 순천시,"전라남도 순천시 충효로 109 (조례동, 디지털프라자전자랜드) 조례동 1264",061-902-7288
1,오류동점,서울 구로구,"서울특별시 구로구 경인로 224 (오류동, 칸타빌레5차) .",02-2625-4854
2,부천역점,경기 고양시 일산동구,"경기도 부천시 부일로 448 (심곡동, 프리존빌딩) 110호, 204호",032-665-8255
3,화성병점점,경기 화성시,"경기도 화성시 병점동로 105 1,2층(진안동)",031-233-4686
4,군산은파유원지DI점,전북 군산시,전라북도 군산시 백토로 284-35 (나운동) .,.
...,...,...,...,...
513,부산달맞이점,부산 해운대구,"부산광역시 해운대구 달맞이길 199, 2~3층 (중동 1488-14) 할리스",051-731-3410
514,신흥역점,경기 성남시 수정구,경기도 성남시 수정구 산성대로 265 (신흥동) 2층 할리스,031-626-6140
515,신림점,서울 관악구,서울특별시 관악구 신림로 353-1,02-877-0019
516,태평로점,서울 중구,"서울특별시 중구 세종대로 64, 해남빌딩 1층 (태평로2가 70-5) 할리스",02-755-7795
517,신촌점,서울 서대문구,서울특별시 서대문구 연세로 34 (창천동 31-12) 할리스,02-393-2004

In [11]:
unique_areas = df['위치(시,구)'].unique()

In [14]:
unique_areas

array(['전남 순천시', '서울 구로구', '경기 고양시 일산동구', '경기 화성시', '전북 군산시', '서울 송파구',
       '경북 구미시', '서울 강서구', '서울 양천구', '인천 부평구', '서울 은평구', '울산 남구', '울산 중구',
       '제주 제주시', '서울 중구', '서울 광진구', '서울 강동구', '제주 서귀포시', '서울 마포구',
       '서울 노원구', '충북 청주시 청원구', '전북 전주시 덕진구', '서울 금천구', '경남 진주시', '강원 원주시',
       '충북 청주시 흥덕구', '충남 천안시 동남구', '충남 공주시', '경기 의정부시', '경기 고양시 덕양구',
       '서울 강남구', '경기 수원시', '서울 용산구', '대구 서구', '전북 전주시 완산구', '부산 북구',
       '서울 서초구', '광주 북구', '강원 홍천군', '부산 부산진구', '충남 홍성군', '경기 성남시',
       '경남 김해시', '서울 서대문구', '부산 기장군', '경기 이천시', '대전 유성구', '서울 종로구',
       '부산 사하구', '경기 광명시', '경기 시흥시', '경기 평택시', '서울 동작구', '경기 하남시',
       '경기 군포시', '대구 달성군', '경기 부천시', '충남 아산시', '경기 성남시 중원구', '부산 서구',
       '대구 북구', '울산 울주군', '경남 창원시 마산회원구', '경남 창원시 진해구', '전북 익산시',
       '경기 고양시 일산서구', '대전 서구', '경남 거제시', '부산 강서구', '경기 성남시 분당구',
       '경남 창원시 마산합포구', '충북 옥천군', '경기 구리시', '경기 안성시', '전남 나주시', '인천 연수구',
       '경기 남양주시', '경기 김포시', '세종', '대구 동구', '서울 영등포구', '충북 청주시 서원구',
       '서울 강북구', '경북 성주군', '강원 속초시', '인천 서구', '서울 관악구', '대구 수성구',
       '부산 수영구', '부산 사상구', '부산 해운대구', '경남 창원시 성산구', '경기 안산시 단원구',
       '경기 오산시', '서울 중랑구', '강원 양양군', '경기 안산시 상록구', '경기 양주시', '경기 파주시',
       '강원 인제군', '대전 동구', '충남 당진시', '경기 수원시 권선구', '경기 안양시 동안구', '경북 칠곡군',
       '인천 남동구', '경남 밀양시', '경기 양평군', '충남 서천군', '전남 광양시', '대구 달서구',
       '충북 청주시 상당구', '인천 중구', '충남 천안시 서북구', '광주 광산구', '경기 수원시 영통구',
       '세종 세종시', '대전 대덕구', '충남 예산군', '경기 용인시 처인구', '부산 금정구', '전북 부안군',
       '서울 성동구', '경남 양산시', '부산 동래구', '경북 경주시', '울산 북구', '전북 김제시', '대전 중구',
       '전남 장흥군', '경기 부천시 원미구', '경남 창원시 의창구', '부산 연제구', '대구 중구', '인천 남구',
       '충북 괴산군', '전남 보성군', '경북 김천시', '전남 무안군', '부산 중구', '부산 동구', '전남 목포시',
       '광주 서구', '경남 사천시', '강원 동해시', '경북 경산시', '경북 군위군', '전북 남원시',
       '전남 여수시', '경기 안양시', '충북 단양군', '광주 동구', '전북 고창군', '경남 거창군',
       '충북 진천군', '강원 강릉시', '경북 문경시', '부산 남구', '경기 수원시 팔달구', '경기 성남시 수정구'],
      dtype=object)

In [1]:
while True:
    n = input('검색할 매장의 도시를 입력하세요: ')
    if n == 'quit':
        print('종료합니다.')
        break
    else:
        if n in unique_areas:
            print('-'*20)
            print(f'검색된 매장 수: {len(df[n])}')
            print('-'*20)
            # for n in unique_areas:
            #     print()

NameError: name 'unique_areas' is not defined